export GAMES_GENERATIONS: Object = {
  'red': {name: 'gen-rby', fullName: 'Red • Blue • Yellow', number: 1},
  'green': {name: 'gen-rby', fullName: 'Red • Blue • Yellow', number: 1},
  'blue': {name: 'gen-rby', fullName: 'Red • Blue • Yellow', number: 1},
  'yellow': {name: 'gen-rby', fullName: 'Red • Blue • Yellow', number: 1},
  'gold': {name: 'gen-gsc', fullName: 'Gold • Silver • Crystal', number: 2},
  'silver': {name: 'gen-gsc', fullName: 'Gold • Silver • Crystal', number: 2},
  'crystal': {name: 'gen-gsc', fullName: 'Gold • Silver • Crystal', number: 2},
  'ruby': {name: 'gen-rse', fullName: 'Ruby • Saphire • Emerald', number: 3},
  'sapphire': {name: 'gen-rse', fullName: 'Ruby • Saphire • Emerald', number: 3},
  'emerald': {name: 'gen-rse', fullName: 'Ruby • Saphire • Emerald', number: 3},
  'firered': {name: 'gen-frlg', fullName: 'FireRed • LeafGreen', number: 3},
  'leafgreen': {name: 'gen-frlg', fullName: 'FireRed • LeafGreen', number: 3},
  'diamond': {name: 'gen-dpp', fullName: 'Diamond • Pearl • Platinum', number: 4},
  'pearl': {name: 'gen-dpp', fullName: 'Diamond • Pearl • Platinum', number: 4},
  'platinum': {name: 'gen-dpp', fullName: 'Diamond • Pearl • Platinum', number: 4},
  'heartgold': {name: 'gen-hgss', fullName: 'HeartGold • SoulSilver', number: 4},
  'soulsilver': {name: 'gen-hgss', fullName: 'HeartGold • SoulSilver', number: 4},
  'black': {name: 'gen-bw', fullName: 'Black • White', number: 5},
  'white': {name: 'gen-bw', fullName: 'Black • White', number: 5},
  'black-2': {name: 'gen-bw', fullName: 'Black • White', number: 5},
  'white-2': {name: 'gen-bw', fullName: 'Black • White', number: 5},
  //Missing X/Y, Ruby/Saphire and Sun/Moon
}
